"""Emit the v3 sweep-best 119 G coefficients as Lean ℚ expressions.

The sweep-best point of `_cohn_elkies_128_v3.py` is

    (delta_1, delta_2, lambda_1) = (0.138, 0.046, 0.85)
    M_cert >= 1.289841061

but its 119 a_j are *not* persisted in `_cohn_elkies_128_v3_results.json`
(v3 re-runs `solve_qp(delta_2, lambda_1)` on-the-fly).  This helper:

  1. Re-runs `solve_qp` for (delta_2 = 0.046, lambda_1 = 0.85) using the
     same cvxpy QP as `_cohn_elkies_128_v3.solve_qp`, with denominator
     1e12 rationalisation.
  2. Re-certifies the four anchors (k_1, S_1, min_G, K_2) at 256-bit prec
     and confirms M_cert >= 1.2898 (sanity check before emission).
  3. Saves the 119 a_j as a JSON file `_cohn_elkies_128_v3_sweepbest_coeffs.json`
     in the same `{"coeffs_num_den": [[n, d], ...]}` schema that
     `_cohn_elkies_128_v3.load_coeffs_from_json` consumes.
  4. Emits a `.lean` snippet (a List ℚ) at
     `_cohn_elkies_128_v3_sweepbest_coeffs.lean`, suitable for `#include`
     into `Cascade129.lean` if/when the coefficients are needed inside
     Lean (currently the Lean theorem only uses rational anchors, so the
     emitted list is archival).

Reproducibility:  the QP is deterministic up to MOSEK/CLARABEL/SCS
solver tie-breaking; we use whichever returns first.  Subsequent runs
*may* differ in the ~9-th decimal of a_j; the certification is robust
because the anchors are recomputed every time.
"""

from __future__ import annotations

import json
import time
from fractions import Fraction
from pathlib import Path

import sys

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE))

# Import the v3 module by file name (it has hyphens-free name).
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location(
    "_cohn_elkies_128_v3", _HERE / "_cohn_elkies_128_v3.py"
)
_v3 = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_v3)


def main() -> None:
    delta_2 = Fraction(46, 1000)      # 0.046
    lambda_1 = Fraction(85, 100)       # 0.85

    print("=" * 74)
    print("Emit v3 sweep-best G coefficients to JSON + Lean snippet")
    print("=" * 74)
    print(f"  Target point: delta_1 = 138/1000 = 0.138")
    print(f"                delta_2 = 46/1000  = 0.046")
    print(f"                lambda_1 = 85/100  = 0.85")
    print()

    # (1) Configure flint precision (solve_qp uses float, but other anchors need it).
    _v3.configure_precision(256)

    # (2) Re-solve the QP.
    print("[1/3] Re-solving QP (119 modes, 5001-point feasibility grid)...")
    t0 = time.time()
    a_opt = _v3.solve_qp(delta_2, lambda_1)
    coeffs_q = _v3.round_to_rationals(a_opt, _v3.RATIONAL_DEN)
    print(f"        done in {time.time() - t0:.1f}s   (n_modes = {len(coeffs_q)})")
    print()

    # (3) Re-certify at the same point at XI_MAX = 1e5 (sweep best was at 1e5).
    print("[2/3] Re-certifying at XI_MAX = 100000, prec = 256 bits...")
    r = _v3.certify_combined(delta_2, lambda_1, coeffs_q,
                             xi_max=10**5, prec_bits=256, verbose=True)
    print()
    M = r["M_cert_lower"]
    if M < 1.2898:
        raise SystemExit(
            f"FAIL: re-cert at sweep-best yields M_cert = {M:.8f}, "
            f"below 1.2898 target."
        )
    print(f"  OK: M_cert_lower = {M:.8f} >= 1.2898")
    print()

    # (4) Save JSON in v3-loader-compatible schema.
    out_json = {
        "delta_1": [_v3.DELTA1_Q.numerator, _v3.DELTA1_Q.denominator],
        "delta_2": [delta_2.numerator, delta_2.denominator],
        "lambda_1": [lambda_1.numerator, lambda_1.denominator],
        "coeffs_num_den": [[q.numerator, q.denominator] for q in coeffs_q],
        "certified_anchors": {
            "k_1_mid": r["k_1_mid"],
            "min_G_lower": r["min_G_lower"],
            "S_1_upper": r["S_1_upper"],
            "K_2_upper": r["K_2_upper"],
            "a_gain_lower": r["a_gain_lower"],
            "M_cert_lower": r["M_cert_lower"],
        },
        "provenance": {
            "script": "_cohn_elkies_128_v3.py + _lean_emit_v3_g_coeffs.py",
            "xi_max": 10**5,
            "prec_bits": 256,
            "arb_grid": _v3.ARB_GRID_DEFAULT,
            "rational_denom": _v3.RATIONAL_DEN,
        },
    }
    json_path = _HERE / "_cohn_elkies_128_v3_sweepbest_coeffs.json"
    with open(json_path, "w") as f:
        json.dump(out_json, f, indent=2)
    print(f"[3/3] Saved JSON: {json_path}")

    # (5) Emit Lean snippet (List ℚ with comments).
    lean_lines = [
        "/- Auto-generated by `_lean_emit_v3_g_coeffs.py`. Do not edit by hand.",
        "   119 G coefficients for the Cascade-129 sweep-best point",
        "   (delta_1, delta_2, lambda_1) = (138/1000, 46/1000, 85/100).",
        f"   Certified M_cert_lower >= {M:.8f} via _cohn_elkies_128_v3.py.",
        "   Each entry is an exact ℚ over denominator 10^12. -/",
        "",
        "namespace Sidon.Cascade129",
        "",
        "/-- 119 G-coefficients (sweep-best, denominator 10^12). -/",
        "def v3_sweepbest_coeffs : List ℚ := [",
    ]
    for j, q in enumerate(coeffs_q, start=1):
        comma = "," if j < len(coeffs_q) else ""
        lean_lines.append(
            f"  (({q.numerator} : ℚ) / {q.denominator}){comma}  -- a_{j}"
        )
    lean_lines.append("]")
    lean_lines.append("")
    lean_lines.append("end Sidon.Cascade129")

    lean_path = _HERE / "_cohn_elkies_128_v3_sweepbest_coeffs.lean"
    with open(lean_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lean_lines) + "\n")
    print(f"        Saved Lean snippet: {lean_path}")
    print()
    print("Summary of certified anchors at sweep-best point:")
    print(f"  k_1   >= {r['k_1_mid']:.10f}    (rad ~ {r['k_1_rad']:.1e})")
    print(f"  min_G >= {r['min_G_lower']:.8f}")
    print(f"  S_1   <= {r['S_1_upper']:.6f}")
    print(f"  K_2   <= {r['K_2_upper']:.8f}")
    print(f"  gain  >= {r['a_gain_lower']:.8f}")
    print(f"  M*    >= {M:.8f}")
    print("=" * 74)


if __name__ == "__main__":
    main()
